import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
       <header
  style={{
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem 2rem',
    background: '#e2096375',
    borderBottom: '1px solid #60b010ff',
    boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  }}
>
  {/* Logo & Title */}
  <Link
    href="/"
    style={{
      display: 'flex',
      alignItems: 'center',
      textDecoration: 'none',
      color: '#9faf21',
      fontWeight: 'bold',
      fontSize: '1.5rem',
      gap: '0.5rem',
    }}
  >
    <img
      src="/logo.jpg"
      alt="Logo"
      style={{ height: '40px', width: 'auto', objectFit: 'contain' }}
    />
    <span style={{ fontFamily: 'sans-serif' }}>My Project</span>
  </Link>

  {/* Navigation */}
  <nav style={{ display: 'flex', gap: '1.5rem' }}>
    <Link
      href="/"
      style={{
        textDecoration: 'none',
        color: '#fff',
        fontSize: '1rem',
        fontWeight: 500,
      }}
    >
      Home
    </Link>
    <Link
      href="/products"
      style={{
        textDecoration: 'none',
        color: '#fff',
        fontSize: '1rem',
        fontWeight: 500,
      }}
    >
      Products
    </Link>
  </nav>
</header>

        {children}

        <footer style={{
          fontSize: '1rem',
          textAlign: 'center',
          color: 'blue',
          padding: '1rem',
          background: 'lightgray'
        }}>
          © 2023 My Project
        </footer>
      </body>
    </html>
  );
}