import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header style={{ fontSize: "2rem", fontWeight: "bold", color: "red", background: "lightgray" }}>My Project</header>
        {children}
        <footer style={{ fontSize: "1rem", textAlign: "center", color: "blue", padding: "1rem", background: "lightgray" }}>
          © 2023 My Project
        </footer>
      </body>
    </html>
  );
}
